### ISSUE TITLE
T3sponsors für TYPO3 6.2

### ISSUE THREAD

**Issue by bastians** [digedag/t3sponsors#2]
T3sponsors läuft leider nicht unter TYPO3 6.2. Gibt es Möglichkeiten, das anzupassen?

**Comment by digedag** [comment]
Ich wüsste nicht, warum es unter 6.2 nicht funktionieren sollte. Da habe ich es schon länger im Einsatz. Eine Anpassung für 7.6 ist noch nicht erfolgt.

**Comment by bastians** [comment]
Oh, ok. Ich erhalte einen Internal Server Error auf Seiten, auf denen ein T3Sponsor-Plugin integriert ist.

**Comment by digedag** [comment]
Ich gehe davon aus, daß du den aktuellen Master hier aus Github verwendest! Hast du mal versucht auf einer neuen Seite ein neues Plugin anzulegen? Internal Server Errors ohne eine Fehlermeldung im PHP-Log haben manchmal andere Ursachen...

**Comment by bastians** [comment]
Ach herrje. Ich dachte die Version hier wäre die selbe wie im TER. Hab nun die Master-Version hochgeladen, läuft! Danke für deine Hilfe :)

Ist die bewusst nicht im TER?
