### ISSUE TITLE
Kategorien via TS greifen nicht

### ISSUE THREAD

**Issue by bastians** [digedag/t3sponsors#4]
Ich möchte beim Einsatz der Extension t3sponsors für das Listenansichten Modul via TS die Sponsoren-Kategorie setzen, und zwar in einer übergeordneten Seite, sodass für alle untergeordneten Seiten mit dem Modul nur Sponsoren einer bestimmten Kategorie angezeigt werden. 
Nach einigen Versuchen und unter Zuhilfenahme des Object Browsers sollte das eigentlich mit folgendem TS klappen:

plugin.tx_t3sponsors {
  sponsorlist {
    options.debug = 1
    categories = 24
    sponsor =< lib.t3sponsors.sponsor
  }
}
Leider greift die Eingrenzung nicht. Auch das Debugging funktioniert an dieser Stelle nicht.

Woran könnte das liegen?

**Comment by digedag** [comment]
Der Filter ist ja auch im Flexform drin. Da kann man sich das rauskopieren:

sponsorlist.sponsor.filter.fields.CATMM.UID_LOCAL.OP_IN_INT = 24

Für den debug dann

sponsorlist.sponsor.filter.options.debug = 1

**Comment by bastians** [comment]
Sehr gut, das klappt. Wobei `plugin.tx_t3sponsors.sponsorlist.categories = 24` für mich logischer aussieht ;)

**Comment by digedag** [comment]
Die Angabe **categories** ist sicher einfacher, logischer ist aber der lange Wert! :wink: 

```
sponsorlist.             -> der View
sponsor.                 -> das Datenobjekt
filter.                  -> Konfiguration für den Filter der Liste
fields.                  -> Felder der Filterbedingung setzen
CATMM.                   -> Alias für die MM-Tabelle zwischen der Kategorie und dem Sponsor
UID_LOCAL.               -> Spalte in der Datenbank mit der UID der Kategorie
OP_IN_INT                -> der Vergleichsoperator. Hier ein **IN ()**. Damit kann man eine Liste von UIDs setzen
```

Wenn du das Prinzip verstehst und die Aliase für die Tabellen kennst, dann kannst du beliebige Filter setzen.

**Comment by bastians** [comment]
Cool, danke. Kann ich das auch auf die T3Sports-Extensions übertragen?

**Comment by digedag** [comment]
Na klar. Die Struktur ist immer ähnlich. Die Ebene _filter_ fehlt nur leider manchmal.

**Comment by bastians** [comment]
Ok, dann spiele ich mal damit rum. Könnte ich damit auch auf Teamnotizen einschränken? Ich suche immernoch eine Möglichkeit, in Teams nur Spieler mit einer bestimmten Teamnotiz anzuzeigen. (Falscher Task, ich weiß ;) )

**Comment by digedag** [comment]
Nein, da geht es leider nicht. Der Filter "kennt" die Tabelle mit den Team-Notizen leider noch nicht. Aber wenn man das implementieren würde, wäre das sicher der richtige Weg für dein Problem.

**Comment by bastians** [comment]
Okee, schade, aber danke :)
