### ISSUE TITLE
Class 't3lib_svbase' not found-Error unter TYPO3 7.6

### ISSUE THREAD

**Issue by bastians** [digedag/t3sponsors#6]
Ich erhalte unter TYPO3 7.6. folgenden Error, nachdem ich die Extension nach dem Upgrade von 6.2 auf 7.6. wieder installiert habe:

> Class 't3lib_svbase' not found in [...]/typo3conf/ext/t3sponsors/sv1/class.tx_t3sponsors_sv1_Sponsor.php on line 33

Mir ist bewusst, dass die Extension aktuell offiziell nicht unter 7.6 läuft, in einem Test vor ein paar lief sie m.E. aber.

Bekomme ich das irgendwie gelöst? :)

**Comment by bastians** [comment]
Kann es sein, dass ich die Extension "div2007" benötige? Wenn ich T3sponsors wieder deinstalliere, div2007 installiere und dann T3sponsors wieder installiere, dann ist der Fehler weg und alles funktioniert wieder.

**Comment by digedag** [comment]
Die Extension div2007 wird nicht verwendet. Vermutlich hast du irgendwie den Compat-Modus aktiviert. Dann wird die fehlende Klasse wieder gefunden.
Ich hab jetzt ein Update hochgeschoben. Damit sollte alles wieder funktionieren. Vermutlich auch unter 8.7. Das hab ich aber nicht getestet... :grin:

**Comment by bastians** [comment]
Was meinst du mit Compat-Modus? Diese compatability-Extension? Die habe ich bewusst nicht installiert.

Aber danke für die Anpassung! Teste ich direkt heute Abend :)

**Comment by bastians** [comment]
Funktioniert mit TYPO3 6.2 und 7.6 👍 

Danke nochmals!
